[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 1
via_ir = true
bytecode_hash = "ipfs"
fs_permissions = [
  { access = "read", path = "./dist" },
  { access = "read", path = "./tmp" },
]

[rpc_endpoints]
edgen = "https://rpc.layeredge.io"
